---
functional:
  - Пользователь должен иметь возможность просмотра баттла других игроков в режиме онлайн
  - Пользователь должен иметь возможность создавать баттл
  - Пользователь должен иметь возможность завершать баттл досрочно
  - Пользователь должен иметь возможность менять язык программирования во время баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Yandex, Chrome, Firefox)
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Участники баттла не могут вводить и редактировать код в терминале соперника
  - Наблюдатели не могут вводить и редактировать код в терминале участников баттла
